### ISSUE TITLE
.djvu file crash on linux.

### ISSUE THREAD

**Issue by ApostolosB** [vtorri/etui#19]
Etui crashes when opening a. djvu file on linux.

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `etui Desktop/sample.djvu'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xaa576380 in ?? () from /usr/lib/libdjvulibre.so.21
[Current thread is 1 (Thread 0xaa430b40 (LWP 710))]
(gdb) bt
#0  0xaa576380 in  () at /usr/lib/libdjvulibre.so.21
#1  0xaa577627 in  () at /usr/lib/libdjvulibre.so.21
#2  0xaa57fd6b in ddjvu_page_render () at /usr/lib/libdjvulibre.so.21
#3  0xaa602f14 in _etui_djvu_page_render (d=0x90e7998) at src/modules/djvu/etui_module_djvu.c:532
#4  0xb770db66 in _etui_smart_page_render (data=0x90e7888, thread=0x9170af0) at src/lib/etui_smart.c:282
#5  0xb71ae343 in _ecore_short_job (thread=2856520512) at lib/ecore/ecore_thread.c:387
#6  0xb71ae99d in _ecore_thread_worker (data=0x0) at lib/ecore/ecore_thread.c:501
#7  0xb6e81c16 in _eina_internal_call (context=0x9108388) at lib/eina/eina_thread.c:151
#8  0xb6bf70f4 in start_thread () at /usr/lib/libpthread.so.0
#9  0xb6d694a6 in clone () at /usr/lib/libc.so.6
(gdb)

```

**Comment by vtorri** [comment]
not a bug in Etui but with wayland over ssh (as it works with software engine)
