### ISSUE TITLE
PDF file crash on linux. 

### ISSUE THREAD

**Issue by NuLogicSystems** [vtorri/etui#24]
```
Starting program: /usr/bin/etui
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/libeo.so.1.20.99-gdb.py", line 7, in <module>
    import eo_gdb
  File "/usr/share/eo/gdb/eo_gdb.py", line 59, in <module>
    null_void_ptr = gdb.parse_and_eval('(_Eo_Object *) 0')
gdb.error: No symbol table is loaded.  Use the "file" command.
[New Thread 0x7fffe93ee700 (LWP 9125)]
[New Thread 0x7fffe5129700 (LWP 9127)]
[Thread 0x7fffe5129700 (LWP 9127) exited]
[New Thread 0x7fffe4928700 (LWP 9128)]
[New Thread 0x7fffdffff700 (LWP 9129)]
[New Thread 0x7fffda641700 (LWP 9130)]
[New Thread 0x7fffd8b80700 (LWP 9131)]
[Thread 0x7fffd8b80700 (LWP 9131) exited]
ERR<9121>:elementary lib/elementary/efl_ui_focus_manager_calc.c:1119 _logical_movement() Warning cycle detected

[New Thread 0x7fffd837f700 (LWP 9132)]
[Thread 0x7fffd837f700 (LWP 9132) exited]
[New Thread 0x7fffd7b7e700 (LWP 9133)]
[New Thread 0x7fffd737d700 (LWP 9134)]
[Thread 0x7fffd737d700 (LWP 9134) exited]
[New Thread 0x7fffd6b7c700 (LWP 9135)]
[Thread 0x7fffd6b7c700 (LWP 9135) exited]
[New Thread 0x7fffd6b7c700 (LWP 9136)]
[Thread 0x7fffd6b7c700 (LWP 9136) exited]
[New Thread 0x7fffd6b7c700 (LWP 9137)]
[New Thread 0x7fffd737d700 (LWP 9138)]
[New Thread 0x7fffd837f700 (LWP 9139)]
[Thread 0x7fffd737d700 (LWP 9138) exited]
[New Thread 0x7fffd8b80700 (LWP 9140)]
[Thread 0x7fffd837f700 (LWP 9139) exited]
[New Thread 0x7fffd637b700 (LWP 9141)]
[New Thread 0x7fffd5b7a700 (LWP 9142)]
[New Thread 0x7fffd5379700 (LWP 9143)]
[New Thread 0x7fffd4b78700 (LWP 9144)]
[New Thread 0x7fffbffff700 (LWP 9145)]
[Thread 0x7fffd8b80700 (LWP 9140) exited]
[New Thread 0x7fffbf7fe700 (LWP 9146)]
[New Thread 0x7fffbeffd700 (LWP 9147)]
[Thread 0x7fffd4b78700 (LWP 9144) exited]
[Thread 0x7fffd5b7a700 (LWP 9142) exited]
[Thread 0x7fffd637b700 (LWP 9141) exited]
[Thread 0x7fffd5379700 (LWP 9143) exited]
[New Thread 0x7fffbe7fc700 (LWP 9148)]
[New Thread 0x7fffbdffb700 (LWP 9149)]
[New Thread 0x7fffbd7fa700 (LWP 9150)]
[New Thread 0x7fffbcff9700 (LWP 9151)]
[Thread 0x7fffbdffb700 (LWP 9149) exited]
[Thread 0x7fffbd7fa700 (LWP 9150) exited]
[New Thread 0x7fffb7fff700 (LWP 9152)]
[New Thread 0x7fffb77fe700 (LWP 9153)]
[Thread 0x7fffbeffd700 (LWP 9147) exited]
[Thread 0x7fffbf7fe700 (LWP 9146) exited]
[Thread 0x7fffd6b7c700 (LWP 9137) exited]
[New Thread 0x7fffb6ffd700 (LWP 9154)]
[Thread 0x7fffbcff9700 (LWP 9151) exited]
[Thread 0x7fffbe7fc700 (LWP 9148) exited]
[New Thread 0x7fffb67fc700 (LWP 9155)]
[Thread 0x7fffbffff700 (LWP 9145) exited]
[New Thread 0x7fffb5ffb700 (LWP 9156)]
[New Thread 0x7fffb57fa700 (LWP 9157)]
[Thread 0x7fffb77fe700 (LWP 9153) exited]
[Thread 0x7fffb7fff700 (LWP 9152) exited]
[New Thread 0x7fffb4ff9700 (LWP 9158)]
[Thread 0x7fffb5ffb700 (LWP 9156) exited]
[New Thread 0x7fffb47f8700 (LWP 9159)]
[New Thread 0x7fffb3ff7700 (LWP 9160)]
[New Thread 0x7fffb37f6700 (LWP 9161)]
[Thread 0x7fffb47f8700 (LWP 9159) exited]
[Thread 0x7fffb57fa700 (LWP 9157) exited]
[New Thread 0x7fffb2ff5700 (LWP 9162)]
[New Thread 0x7fffb27f4700 (LWP 9163)]
[Thread 0x7fffb3ff7700 (LWP 9160) exited]
[Thread 0x7fffb67fc700 (LWP 9155) exited]
[Thread 0x7fffb6ffd700 (LWP 9154) exited]
[Thread 0x7fffb4ff9700 (LWP 9158) exited]
[New Thread 0x7fffb1ff3700 (LWP 9164)]
[Thread 0x7fffb27f4700 (LWP 9163) exited]
[New Thread 0x7fffb17f2700 (LWP 9165)]
[New Thread 0x7fffb0ff1700 (LWP 9166)]
[Thread 0x7fffb17f2700 (LWP 9165) exited]
[New Thread 0x7fffb07f0700 (LWP 9167)]
[Thread 0x7fffb37f6700 (LWP 9161) exited]
[New Thread 0x7fffaffef700 (LWP 9168)]
[Thread 0x7fffb2ff5700 (LWP 9162) exited]
[New Thread 0x7fffaf7ee700 (LWP 9169)]
[Thread 0x7fffb1ff3700 (LWP 9164) exited]
[New Thread 0x7fffaefed700 (LWP 9170)]
[Thread 0x7fffaffef700 (LWP 9168) exited]
[New Thread 0x7fffae7ec700 (LWP 9171)]
[Thread 0x7fffaf7ee700 (LWP 9169) exited]
[New Thread 0x7fffadfeb700 (LWP 9172)]
[Thread 0x7fffae7ec700 (LWP 9171) exited]
[New Thread 0x7fffad7ea700 (LWP 9173)]
[New Thread 0x7fffacfe9700 (LWP 9174)]
[Thread 0x7fffaefed700 (LWP 9170) exited]
[New Thread 0x7fffac7e8700 (LWP 9175)]
[Thread 0x7fffad7ea700 (LWP 9173) exited]
[New Thread 0x7fffabfe7700 (LWP 9176)]
[Thread 0x7fffacfe9700 (LWP 9174) exited]
[New Thread 0x7fffab7e6700 (LWP 9177)]
[Thread 0x7fffac7e8700 (LWP 9175) exited]
[New Thread 0x7fffaafe5700 (LWP 9178)]
[Thread 0x7fffabfe7700 (LWP 9176) exited]
[New Thread 0x7fffaa7e4700 (LWP 9179)]
[Thread 0x7fffab7e6700 (LWP 9177) exited]
[New Thread 0x7fffa9fe3700 (LWP 9180)]
[Thread 0x7fffb07f0700 (LWP 9167) exited]
[New Thread 0x7fffa97e2700 (LWP 9181)]
[Thread 0x7fffaa7e4700 (LWP 9179) exited]
[New Thread 0x7fffa8fe1700 (LWP 9182)]
[Thread 0x7fffa9fe3700 (LWP 9180) exited]
[Thread 0x7fffaafe5700 (LWP 9178) exited]
[New Thread 0x7fffa87e0700 (LWP 9183)]
[Thread 0x7fffadfeb700 (LWP 9172) exited]
[Thread 0x7fffa87e0700 (LWP 9183) exited]
[Thread 0x7fffa8fe1700 (LWP 9182) exited]
[Thread 0x7fffa97e2700 (LWP 9181) exited]
[Thread 0x7fffb0ff1700 (LWP 9166) exited]
focus in
[New Thread 0x7fffb0ff1700 (LWP 9184)]
[Thread 0x7fffb0ff1700 (LWP 9184) exited]
[New Thread 0x7fffb0ff1700 (LWP 9185)]
[Thread 0x7fffb0ff1700 (LWP 9185) exited]
[New Thread 0x7fffb0ff1700 (LWP 9186)]
[Thread 0x7fffb0ff1700 (LWP 9186) exited]
[New Thread 0x7fffa87e0700 (LWP 9187)]
[Thread 0x7fffa87e0700 (LWP 9187) exited]
[New Thread 0x7fffa97e2700 (LWP 9188)]
[Thread 0x7fffa97e2700 (LWP 9188) exited]
[New Thread 0x7fffa8fe1700 (LWP 9189)]
[Thread 0x7fffa8fe1700 (LWP 9189) exited]
[New Thread 0x7fffd8b80700 (LWP 9190)]
[New Thread 0x7fffd837f700 (LWP 9191)]
[New Thread 0x7fffd737d700 (LWP 9192)]
[New Thread 0x7fffd6b7c700 (LWP 9193)]
[Thread 0x7fffd737d700 (LWP 9192) exited]
[Thread 0x7fffd837f700 (LWP 9191) exited]
[Thread 0x7fffd8b80700 (LWP 9190) exited]
[Thread 0x7fffd6b7c700 (LWP 9193) exited]
[New Thread 0x7fffd637b700 (LWP 9194)]
[Thread 0x7fffd637b700 (LWP 9194) exited]
[New Thread 0x7fffd5b7a700 (LWP 9195)]
[Thread 0x7fffd5b7a700 (LWP 9195) exited]
[New Thread 0x7fffd5379700 (LWP 9196)]
[Thread 0x7fffd5379700 (LWP 9196) exited]
[New Thread 0x7fffd4b78700 (LWP 9197)]
[Thread 0x7fffd4b78700 (LWP 9197) exited]
[New Thread 0x7fffbffff700 (LWP 9198)]
[New Thread 0x7fffbf7fe700 (LWP 9199)]
[Thread 0x7fffbffff700 (LWP 9198) exited]
[New Thread 0x7fffbeffd700 (LWP 9200)]
[Thread 0x7fffbf7fe700 (LWP 9199) exited]
[New Thread 0x7fffbe7fc700 (LWP 9201)]
[Thread 0x7fffbe7fc700 (LWP 9201) exited]
[New Thread 0x7fffbdffb700 (LWP 9202)]
[Thread 0x7fffbeffd700 (LWP 9200) exited]
[Thread 0x7fffbdffb700 (LWP 9202) exited]
[New Thread 0x7fffbd7fa700 (LWP 9203)]
[Thread 0x7fffbd7fa700 (LWP 9203) exited]
[New Thread 0x7fffbcff9700 (LWP 9204)]
[New Thread 0x7fffb7fff700 (LWP 9205)]
[Thread 0x7fffbcff9700 (LWP 9204) exited]
[New Thread 0x7fffb77fe700 (LWP 9206)]
[Thread 0x7fffb7fff700 (LWP 9205) exited]
[New Thread 0x7fffb6ffd700 (LWP 9207)]
[Thread 0x7fffb77fe700 (LWP 9206) exited]
[New Thread 0x7fffb67fc700 (LWP 9208)]
[Thread 0x7fffb6ffd700 (LWP 9207) exited]
[New Thread 0x7fffb5ffb700 (LWP 9209)]
[Thread 0x7fffb67fc700 (LWP 9208) exited]
[New Thread 0x7fffb57fa700 (LWP 9210)]
[Thread 0x7fffb5ffb700 (LWP 9209) exited]
[Thread 0x7fffb57fa700 (LWP 9210) exited]
[New Thread 0x7fffb4ff9700 (LWP 9211)]
[Thread 0x7fffb4ff9700 (LWP 9211) exited]
[New Thread 0x7fffb47f8700 (LWP 9212)]
[New Thread 0x7fffb3ff7700 (LWP 9213)]
[Thread 0x7fffb47f8700 (LWP 9212) exited]
[Thread 0x7fffb3ff7700 (LWP 9213) exited]
[New Thread 0x7fffb37f6700 (LWP 9214)]
[New Thread 0x7fffb2ff5700 (LWP 9215)]
[Thread 0x7fffb37f6700 (LWP 9214) exited]
[Thread 0x7fffb2ff5700 (LWP 9215) exited]
[New Thread 0x7fffb27f4700 (LWP 9216)]
[New Thread 0x7fffb1ff3700 (LWP 9217)]
[Thread 0x7fffb27f4700 (LWP 9216) exited]
[New Thread 0x7fffb17f2700 (LWP 9218)]
[New Thread 0x7fffb07f0700 (LWP 9219)]
[New Thread 0x7fffaffef700 (LWP 9220)]
[New Thread 0x7fffaf7ee700 (LWP 9221)]
[Thread 0x7fffb17f2700 (LWP 9218) exited]
[Thread 0x7fffaffef700 (LWP 9220) exited]
[Thread 0x7fffb1ff3700 (LWP 9217) exited]
[Thread 0x7fffaf7ee700 (LWP 9221) exited]
[Thread 0x7fffb07f0700 (LWP 9219) exited]
[New Thread 0x7fffb1ff3700 (LWP 9222)]
[Thread 0x7fffb1ff3700 (LWP 9222) exited]
[New Thread 0x7fffb1ff3700 (LWP 9226)]
[New Thread 0x7fffb07f0700 (LWP 9227)]
[New Thread 0x7fffaf7ee700 (LWP 9228)]
[New Thread 0x7fffaffef700 (LWP 9229)]
[Thread 0x7fffaf7ee700 (LWP 9228) exited]
[Thread 0x7fffb1ff3700 (LWP 9226) exited]
[Thread 0x7fffaffef700 (LWP 9229) exited]
[Thread 0x7fffb07f0700 (LWP 9227) exited]

Thread 1 "etui" received signal SIGSEGV, Segmentation fault.
0x00007fffd506eded in ?? () from /usr/lib/etui/modules/pdf/linux-gnu-x86_64-0.0.4/module.so
(gdb)
```

**Comment by vtorri** [comment]
fixed in 5fa7c7e
thank you
